expression        -> literal
                  | unary
                  | binary
                  | grouping
                  ;

literal           -> NUMBER | STRING | "true" | "false" | "nil" ;
grouping          -> "(" expression ")" ;
unary             -> ( "-" | "!" ) expression ;
ternary           -> expression operator expression operator expression ;
binary            -> expression operator expression ;
operator          -> "==" | "!=" | "<" | "<=" | ">" | ">="
                  | "+" | "-" | "*" | "/" | "%" | "?" | ":" ;

expression        -> ternary

ternary           -> equality ? equality (: ternary)* ;

equality          -> comparison ( ( "!=" | "==" ) comparison )* ;

comparison        -> term ( ( ">" | ">=" | "<" | "<=" ) term )* ;

term              -> factor ( ( "-" | "+" ) factor )* ;

factor            -> unary ( ( "/" | "*" | "%" ) unary )* ;

unary             -> ( "!"  | "-" ) unary
                  | primary
                  ;

primary           -> NUMBER | STRING | "true" | "false" | "nil"
                  | "(" expression ")"
                  ;


